name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting up Nodejs environment
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Setup environment vars
        run: echo "VITE_API_URL=${{vars.API_URL}}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm ci

      - name: Build static files for Vue
        run: npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 $VPS 'echo connected'

      - name: Deploy via rsync
        run: |
          ls -l ./dist  # optional, debug to see files
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22" \
            ./dist/* $UPLOAD_PATH --delete

      - name: Build image and restart docker
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 $VPS \
          "cd $DOCKER_COMPOSE_PATH && docker compose build && docker compose up -d"

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS: "${{vars.VPS_USER}}@${{vars.VPS_HOST}}"
      UPLOAD_PATH: "${{vars.VPS_USER}}@${{vars.VPS_HOST}}:${{vars.VPS_DIR}}"
      DOCKER_COMPOSE_PATH: "${{vars.VPS_DOCKER_COMPOSE}}"